project:
  type: website

website:
  title: "my_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/icepop0
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lumen
    css: styles.css

editor: visual

